name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  discord_api:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_webview_plugin: ^0.4.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true