name: discord_api
description: A pure dart package wrapping the discord API
version: 0.1.0
homepage: https://github.com/MeixDev/discord_api_flutter
repository: https://github.com/MeixDev/discord_api_flutter

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: ^4.0.4

dev_dependencies:
  coverage: ^1.1.0
  http_mock_adapter: ^0.3.2
  lint: ^1.8.2
  test: ^1.20.1